apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity
  namespace: kube-system
  labels:
    app: identity
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"